const cartActionTypes ={
    TOGGLE_SHOPIPING_CARD : 'TOGGLE_SHOPIPING_CARD',
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM_FROM_CART:'REMOVE_ITEM_FROM_CART',
    DECREMENTE_ITEM_QUANTITY: 'DECREMENTE_ITEM_QUANTITY',
    CLEAR_CART:'CLEAR_CART'
}

export default cartActionTypes;